#pragma once


enum OPTYPE { OP_SEND, OP_RECV, OP_DO_AI, OP_PLAYER_MOVE_NOTIFY, OP_RESPAWN, OP_REVIVAL };

enum NPC_MOVE { NONE, LEFT, RIGHT, UP, DOWN };

enum Event_Type { E_MOVE, E_RESPAWN, E_REVIVAL };

enum AREA {
	BG = 20, VERTICALROAD = 1, HORIZEN_ROAD = 2, S1_LINE = 4, VILLIGE = 15,
	CEN_LINE = 14, VILLIGE_LINE = 19, BOSS_LINE = 18
};
